global:
  resolve_timeout: 5m

route:
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: your_bot_token
        api_url: https://api.telegram.org
        chat_id: your_chat_id
        parse_mode: ''
