# global:
#   scrape_interval: 30s
#   scrape_timeout: 10s
# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['prometheus:9090']
#   - job_name: 'node_exporter'
#     static_configs:
#       - targets: ['node-exporter:9100']

global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
